In [1]:
import numpy as np

arr1 = np.array(
    [[1, 2, 3, 10],
    [4, 5, 6, 11],
    [7, 8, 9, 12],
]
)

np.random.seed(250531)
arr2 = np.random.randint(0, 100, (3, 4))

print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)

print(arr1)
arr1 = arr1.T     #矩阵逆置
print(arr1)

# arr1 = np.reshape(arr1, (1, arr1.size))
arr1 = np.reshape(arr1, (-1))     #展开为一维数组
print(arr1)

'''
np.reshape(arr, (rows, cols))中
cols写-1，让py自行通过rows来计算列数cols
'''

[[31 44  0 95]
 [47 44 30 91]
 [24 45 11 77]]
(3, 4)
2
int32
(3, 4)
2
int32
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [10 11 12]]
[ 1  4  7  2  5  8  3  6  9 10 11 12]


'\nnp.reshape(arr, (rows, cols))中\ncols写-1，让py自行通过rows来计算列数cols\n'